//! HCGF v1: fixed-size metadata for a cross-process GPU frame.
//! This module carries no file descriptors and does not replace HCSF.

pub const HCGF_BYTES: usize = 232;
pub const HCGI_BYTES: usize = 88;

#[cfg(test)]
pub(crate) fn input_geometry_golden() -> Vec<u8> {
    // Generated by the C++ encoder and pinned by its wire test as well.
    let hex = "4843474900010058000000000000123400000000000056780000000000002334c004000000000000400a00000000000040890000000000004082c0000000000040790000000000004072c000000000000000000000000000";
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

/// Source-frozen geometry appended to the SAME seqpacket as HCGF and its FDs.
/// A legacy HCGF-only frame has no usable window-input binding.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct InputGeometry {
    pub window: u64,
    pub surface: u64,
    pub pid: u64,
    pub content: [f64; 4],
    pub surface_extent: [f64; 2],
}

/// # Errors
/// Rejects noncanonical framing, reserved bytes, identities or geometry.
pub fn decode_input_geometry(bytes: &[u8]) -> Result<InputGeometry> {
    if bytes.len() != HCGI_BYTES {
        return Err(HcgfError::Length);
    }
    if &bytes[..4] != b"HCGI" {
        return Err(HcgfError::Magic);
    }
    if bytes[4..6] != [0, 1] {
        return Err(HcgfError::Version);
    }
    if bytes[6..8] != [0, 88] {
        return Err(HcgfError::HeaderLength);
    }
    if u64_at(bytes, 80) != 0 {
        return Err(HcgfError::Reserved);
    }
    let input = InputGeometry {
        window: u64_at(bytes, 8),
        surface: u64_at(bytes, 16),
        pid: u64_at(bytes, 24),
        content: [32, 40, 48, 56].map(|at| f64_at(bytes, at)),
        surface_extent: [64, 72].map(|at| f64_at(bytes, at)),
    };
    if input.window == 0 || input.surface == 0 || input.pid == 0 || input.pid > i32::MAX as u64 {
        return Err(HcgfError::ZeroLineage);
    }
    if input
        .content
        .iter()
        .chain(input.surface_extent.iter())
        .any(|v| !v.is_finite())
        || !(input.content[0] + input.content[2]).is_finite()
        || !(input.content[1] + input.content[3]).is_finite()
    {
        return Err(HcgfError::NonFiniteGeometry);
    }
    if input.content[2..]
        .iter()
        .chain(input.surface_extent.iter())
        .any(|v| *v <= 0.0)
    {
        return Err(HcgfError::Geometry);
    }
    Ok(input)
}
pub const HCGF_MAGIC: [u8; 4] = *b"HCGF";
pub const FORMAT_ABGR8888: u32 = 0x3432_4241;
pub const FLAG_PREMULTIPLIED: u32 = 1;
pub const FLAG_FLIP_Y: u32 = 1 << 1;
pub const FLAG_SHADOW_ENABLED: u32 = 1 << 2;
const KNOWN_FLAGS: u32 = FLAG_PREMULTIPLIED | FLAG_FLIP_Y | FLAG_SHADOW_ENABLED;

#[derive(Clone, Debug, PartialEq)]
pub struct ShadowSnapshot {
    pub left: f64,
    pub top: f64,
    pub width: f64,
    pub height: f64,
    pub cutout_left: f64,
    pub cutout_top: f64,
    pub cutout_width: f64,
    pub cutout_height: f64,
    pub range: f64,
    pub rounding: f64,
    pub window_rounding: f64,
    pub rounding_power: f64,
    pub power: u32,
    pub sharp: bool,
    pub rgba: [u8; 4],
}

#[derive(Clone, Debug, PartialEq)]
pub struct HcgfFrame {
    pub sequence: u64,
    pub capture_monotonic_ns: u64,
    pub geometry_epoch: u64,
    pub logical_x: f64,
    pub logical_y: f64,
    pub logical_width: f64,
    pub logical_height: f64,
    pub image_width: u32,
    pub image_height: u32,
    pub fourcc: u32,
    pub stride: u32,
    pub modifier: u64,
    pub offset: u64,
    pub crop_x: u32,
    pub crop_y: u32,
    pub crop_width: u32,
    pub crop_height: u32,
    pub flip_y: bool,
    pub shadow: Option<ShadowSnapshot>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HcgfError {
    Length,
    Magic,
    Version,
    HeaderLength,
    ZeroLineage,
    NonFiniteGeometry,
    Geometry,
    Format,
    Stride,
    Offset,
    Crop,
    Flags,
    Reserved,
    Shadow,
}

pub type Result<T> = std::result::Result<T, HcgfError>;

fn validate(frame: &HcgfFrame) -> Result<()> {
    if frame.sequence == 0 || frame.capture_monotonic_ns == 0 || frame.geometry_epoch == 0 {
        return Err(HcgfError::ZeroLineage);
    }
    if !frame.logical_x.is_finite()
        || !frame.logical_y.is_finite()
        || !frame.logical_width.is_finite()
        || !frame.logical_height.is_finite()
    {
        return Err(HcgfError::NonFiniteGeometry);
    }
    if frame.logical_width <= 0.0
        || frame.logical_height <= 0.0
        || frame.image_width == 0
        || frame.image_height == 0
        || frame.image_width > i32::MAX as u32
        || frame.image_height > i32::MAX as u32
    {
        return Err(HcgfError::Geometry);
    }
    if frame.fourcc != FORMAT_ABGR8888 {
        return Err(HcgfError::Format);
    }
    let min_stride = frame.image_width.checked_mul(4).ok_or(HcgfError::Stride)?;
    if frame.stride < min_stride || frame.stride > i32::MAX as u32 {
        return Err(HcgfError::Stride);
    }
    if frame.offset > i32::MAX as u64 {
        return Err(HcgfError::Offset);
    }
    if frame.crop_width == 0
        || frame.crop_height == 0
        || frame
            .crop_x
            .checked_add(frame.crop_width)
            .is_none_or(|v| v > frame.image_width)
        || frame
            .crop_y
            .checked_add(frame.crop_height)
            .is_none_or(|v| v > frame.image_height)
    {
        return Err(HcgfError::Crop);
    }
    if let Some(shadow) = &frame.shadow {
        for value in [
            shadow.left,
            shadow.top,
            shadow.width,
            shadow.height,
            shadow.cutout_left,
            shadow.cutout_top,
            shadow.cutout_width,
            shadow.cutout_height,
            shadow.range,
            shadow.rounding,
            shadow.window_rounding,
            shadow.rounding_power,
        ] {
            if !value.is_finite() {
                return Err(HcgfError::Shadow);
            }
        }
        if shadow.width <= 0.0
            || shadow.height <= 0.0
            || shadow.cutout_width <= 0.0
            || shadow.cutout_height <= 0.0
            || shadow.range <= 0.0
            || shadow.rounding < 0.0
            || shadow.window_rounding < 0.0
            || !(1.0..=10.0).contains(&shadow.rounding_power)
            || !(1..=4).contains(&shadow.power)
        {
            return Err(HcgfError::Shadow);
        }
    }
    Ok(())
}

fn put_u32(out: &mut [u8], at: usize, value: u32) {
    out[at..at + 4].copy_from_slice(&value.to_be_bytes());
}
fn put_u64(out: &mut [u8], at: usize, value: u64) {
    out[at..at + 8].copy_from_slice(&value.to_be_bytes());
}
fn put_f64(out: &mut [u8], at: usize, value: f64) {
    put_u64(out, at, value.to_bits());
}
fn u32_at(bytes: &[u8], at: usize) -> u32 {
    u32::from_be_bytes(bytes[at..at + 4].try_into().unwrap())
}
fn u64_at(bytes: &[u8], at: usize) -> u64 {
    u64::from_be_bytes(bytes[at..at + 8].try_into().unwrap())
}
fn f64_at(bytes: &[u8], at: usize) -> f64 {
    f64::from_bits(u64_at(bytes, at))
}

///
/// # Errors
///
/// Returns an error when any frame field violates the HCGF wire contract.
pub fn encode(frame: &HcgfFrame) -> Result<[u8; HCGF_BYTES]> {
    validate(frame)?;
    let mut out = [0u8; HCGF_BYTES];
    out[0..4].copy_from_slice(&HCGF_MAGIC);
    out[4..6].copy_from_slice(&1u16.to_be_bytes());
    out[6..8].copy_from_slice(
        &u16::try_from(HCGF_BYTES)
            .map_err(|_| HcgfError::HeaderLength)?
            .to_be_bytes(),
    );
    put_u64(&mut out, 8, frame.sequence);
    put_u64(&mut out, 16, frame.capture_monotonic_ns);
    put_u64(&mut out, 24, frame.geometry_epoch);
    for (at, value) in [
        (32, frame.logical_x),
        (40, frame.logical_y),
        (48, frame.logical_width),
        (56, frame.logical_height),
    ] {
        put_f64(&mut out, at, value);
    }
    put_u32(&mut out, 64, frame.image_width);
    put_u32(&mut out, 68, frame.image_height);
    put_u32(&mut out, 72, frame.fourcc);
    put_u32(&mut out, 76, frame.stride);
    put_u64(&mut out, 80, frame.modifier);
    put_u64(&mut out, 88, frame.offset);
    put_u32(&mut out, 96, frame.crop_x);
    put_u32(&mut out, 100, frame.crop_y);
    put_u32(&mut out, 104, frame.crop_width);
    put_u32(&mut out, 108, frame.crop_height);
    let flags = FLAG_PREMULTIPLIED
        | if frame.flip_y { FLAG_FLIP_Y } else { 0 }
        | if frame.shadow.is_some() {
            FLAG_SHADOW_ENABLED
        } else {
            0
        };
    put_u32(&mut out, 112, flags);
    if let Some(s) = &frame.shadow {
        for (at, value) in [
            (120, s.left),
            (128, s.top),
            (136, s.width),
            (144, s.height),
            (152, s.cutout_left),
            (160, s.cutout_top),
            (168, s.cutout_width),
            (176, s.cutout_height),
            (184, s.range),
            (192, s.rounding),
            (200, s.window_rounding),
            (208, s.rounding_power),
        ] {
            put_f64(&mut out, at, value);
        }
        put_u32(&mut out, 216, s.power);
        out[220..224].copy_from_slice(&s.rgba);
        put_u32(&mut out, 224, u32::from(s.sharp));
    }
    Ok(out)
}

///
/// # Errors
///
/// Returns an error when the bytes do not contain a valid HCGF v1 frame.
pub fn decode(bytes: &[u8]) -> Result<HcgfFrame> {
    if bytes.len() != HCGF_BYTES {
        return Err(HcgfError::Length);
    }
    if bytes[0..4] != HCGF_MAGIC {
        return Err(HcgfError::Magic);
    }
    if u16::from_be_bytes([bytes[4], bytes[5]]) != 1 {
        return Err(HcgfError::Version);
    }
    if usize::from(u16::from_be_bytes([bytes[6], bytes[7]])) != HCGF_BYTES {
        return Err(HcgfError::HeaderLength);
    }
    if u64_at(bytes, 8) == 0 || u64_at(bytes, 16) == 0 || u64_at(bytes, 24) == 0 {
        return Err(HcgfError::ZeroLineage);
    }
    let flags = u32_at(bytes, 112);
    if flags & FLAG_PREMULTIPLIED == 0 || flags & !KNOWN_FLAGS != 0 {
        return Err(HcgfError::Flags);
    }
    if u32_at(bytes, 116) != 0 || u32_at(bytes, 228) != 0 {
        return Err(HcgfError::Reserved);
    }
    let shadow_enabled = flags & FLAG_SHADOW_ENABLED != 0;
    if !shadow_enabled && bytes[120..232].iter().any(|b| *b != 0) {
        return Err(HcgfError::Shadow);
    }
    let shadow = if shadow_enabled {
        Some(ShadowSnapshot {
            left: f64_at(bytes, 120),
            top: f64_at(bytes, 128),
            width: f64_at(bytes, 136),
            height: f64_at(bytes, 144),
            cutout_left: f64_at(bytes, 152),
            cutout_top: f64_at(bytes, 160),
            cutout_width: f64_at(bytes, 168),
            cutout_height: f64_at(bytes, 176),
            range: f64_at(bytes, 184),
            rounding: f64_at(bytes, 192),
            window_rounding: f64_at(bytes, 200),
            rounding_power: f64_at(bytes, 208),
            power: u32_at(bytes, 216),
            sharp: u32_at(bytes, 224) != 0,
            rgba: [bytes[220], bytes[221], bytes[222], bytes[223]],
        })
    } else {
        None
    };
    if u32_at(bytes, 224) > 1 {
        return Err(HcgfError::Shadow);
    }
    let frame = HcgfFrame {
        sequence: u64_at(bytes, 8),
        capture_monotonic_ns: u64_at(bytes, 16),
        geometry_epoch: u64_at(bytes, 24),
        logical_x: f64_at(bytes, 32),
        logical_y: f64_at(bytes, 40),
        logical_width: f64_at(bytes, 48),
        logical_height: f64_at(bytes, 56),
        image_width: u32_at(bytes, 64),
        image_height: u32_at(bytes, 68),
        fourcc: u32_at(bytes, 72),
        stride: u32_at(bytes, 76),
        modifier: u64_at(bytes, 80),
        offset: u64_at(bytes, 88),
        crop_x: u32_at(bytes, 96),
        crop_y: u32_at(bytes, 100),
        crop_width: u32_at(bytes, 104),
        crop_height: u32_at(bytes, 108),
        flip_y: flags & FLAG_FLIP_Y != 0,
        shadow,
    };
    validate(&frame)?;
    Ok(frame)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn native_input_geometry_golden_and_strict_boundaries() {
        let bytes = input_geometry_golden();
        assert_eq!(
            decode_input_geometry(&bytes).unwrap(),
            InputGeometry {
                window: 0x1234,
                surface: 0x5678,
                pid: 9012,
                content: [-2.5, 3.25, 800.0, 600.0],
                surface_extent: [400.0, 300.0]
            }
        );
        for size in 0..HCGI_BYTES {
            assert!(decode_input_geometry(&bytes[..size]).is_err());
        }
        for (offset, value) in [
            (8, 0),
            (16, 0),
            (24, 0),
            (24, u64::MAX),
            (48, f64::NAN.to_bits()),
            (64, 0),
            (80, 1),
        ] {
            let mut bad = bytes.clone();
            put_u64(&mut bad, offset, value);
            assert!(decode_input_geometry(&bad).is_err());
        }
    }

    fn frame(shadow: Option<ShadowSnapshot>) -> HcgfFrame {
        HcgfFrame {
            sequence: 9,
            capture_monotonic_ns: 1234,
            geometry_epoch: 7,
            logical_x: -2.5,
            logical_y: 3.25,
            logical_width: 800.0,
            logical_height: 600.0,
            image_width: 1600,
            image_height: 1200,
            fourcc: FORMAT_ABGR8888,
            stride: 6400,
            modifier: 0x3000,
            offset: 64,
            crop_x: 4,
            crop_y: 8,
            crop_width: 1592,
            crop_height: 1184,
            flip_y: true,
            shadow,
        }
    }

    fn shadow() -> ShadowSnapshot {
        ShadowSnapshot {
            left: 1.0,
            top: 2.0,
            width: 800.0,
            height: 600.0,
            cutout_left: 8.0,
            cutout_top: 9.0,
            cutout_width: 784.0,
            cutout_height: 584.0,
            range: 24.0,
            rounding: 12.0,
            window_rounding: 10.0,
            rounding_power: 2.0,
            power: 3,
            sharp: true,
            rgba: [1, 2, 3, 4],
        }
    }

    #[test]
    fn exact_roundtrip_and_offsets() {
        let encoded = encode(&frame(Some(shadow()))).unwrap();
        assert_eq!(&encoded[0..4], b"HCGF");
        assert_eq!(&encoded[4..6], &1u16.to_be_bytes());
        assert_eq!(&encoded[6..8], &232u16.to_be_bytes());
        assert_eq!(encoded[72..76], FORMAT_ABGR8888.to_be_bytes());
        assert_eq!(encoded[216..220], 3u32.to_be_bytes());
        assert_eq!(&encoded[220..224], &[1, 2, 3, 4]);
        assert_eq!(encoded[224..228], 1u32.to_be_bytes());
        assert_eq!(decode(&encoded).unwrap(), frame(Some(shadow())));
    }

    #[test]
    fn disabled_shadow_zeroes_entire_shadow_region() {
        let encoded = encode(&frame(None)).unwrap();
        assert!(encoded[120..232].iter().all(|b| *b == 0));
        assert_eq!(decode(&encoded).unwrap(), frame(None));
        for at in 120..232 {
            let mut bad = encoded;
            bad[at] = 1;
            assert!(decode(&bad).is_err(), "offset {at}");
        }
    }

    #[test]
    fn rejects_length_reserved_flags_nan_and_overflow() {
        let encoded = encode(&frame(Some(shadow()))).unwrap();
        assert_eq!(decode(&encoded[..231]), Err(HcgfError::Length));
        let mut extra = encoded.to_vec();
        extra.push(0);
        assert_eq!(decode(&extra), Err(HcgfError::Length));
        let mut bad = encoded;
        bad[116] = 1;
        assert_eq!(decode(&bad), Err(HcgfError::Reserved));
        let mut bad = encoded;
        bad[112..116].copy_from_slice(&(8u32).to_be_bytes());
        assert_eq!(decode(&bad), Err(HcgfError::Flags));
        let mut bad = encoded;
        bad[32..40].copy_from_slice(&f64::NAN.to_bits().to_be_bytes());
        assert_eq!(decode(&bad), Err(HcgfError::NonFiniteGeometry));
        let mut bad = encoded;
        bad[96..100].copy_from_slice(&u32::MAX.to_be_bytes());
        assert_eq!(decode(&bad), Err(HcgfError::Crop));
    }

    #[test]
    fn rejects_invalid_frame_fields() {
        let mut f = frame(None);
        f.sequence = 0;
        assert_eq!(encode(&f), Err(HcgfError::ZeroLineage));
        let mut f = frame(None);
        f.fourcc = 0;
        assert_eq!(encode(&f), Err(HcgfError::Format));
        let mut f = frame(None);
        f.stride = 4;
        assert_eq!(encode(&f), Err(HcgfError::Stride));
        let mut f = frame(None);
        f.image_height = i32::MAX as u32 + 1;
        assert_eq!(encode(&f), Err(HcgfError::Geometry));
        let mut f = frame(Some(shadow()));
        f.shadow.as_mut().unwrap().rounding_power = 11.0;
        assert_eq!(encode(&f), Err(HcgfError::Shadow));
    }
}
