#include "vfgp_parser.h"
#include <algorithm>
#include <fstream>
#include <iostream>
using namespace viewflow::vfgp;
static void u32(std::vector<uint8_t>&b,uint32_t x){b.insert(b.end(),{uint8_t(x>>24),uint8_t(x>>16),uint8_t(x>>8),uint8_t(x)});} static void u64(std::vector<uint8_t>&b,uint64_t x){u32(b,uint32_t(x>>32));u32(b,uint32_t(x));}
static std::vector<uint8_t> vfar(uint32_t w,uint32_t h,uint8_t m,std::vector<uint8_t> p){std::vector<uint8_t>b{'V','F','A','R',1,m,0,0};u32(b,w);u32(b,h);u64(b,uint64_t(w)*h);b.insert(b.end(),p.begin(),p.end());return b;}
static std::vector<uint8_t> frame(uint8_t v,uint64_t id,uint32_t w,uint32_t h,std::vector<uint8_t> c,std::vector<uint8_t>a){std::vector<uint8_t>b{'V','F','G','P',v,uint8_t(v==3),0,0};u32(b,40);u32(b,uint32_t(c.size()+a.size()));u64(b,id);u32(b,w);u32(b,h);u32(b,uint32_t(c.size()));u32(b,uint32_t(a.size()));b.insert(b.end(),c.begin(),c.end());b.insert(b.end(),a.begin(),a.end());return b;}
int main(int n,char**v){auto one=frame(1,9,2,2,{1,2,3},{4,5,6,7});auto raw=frame(2,10,2,2,{8,9,10},vfar(2,2,0,{11,12,13,14}));auto rle=frame(2,11,2,4,{15,16,17},vfar(2,4,1,{0x83,21,0x03,22,23,24,25}));auto warm=frame(3,12,2,2,{18,19,20},vfar(2,2,0,{1,2,3,4}));auto wire=one;wire.insert(wire.end(),raw.begin(),raw.end());wire.insert(wire.end(),rle.begin(),rle.end());wire.insert(wire.end(),warm.begin(),warm.end());Parser p;std::vector<Frame>f;for(size_t at=0;at<wire.size();){auto take=(std::min)(size_t(13),wire.size()-at);if(!p.Push({wire.data()+at,take},&f))return 1;at+=take;}if(!p.Finish()||f.size()!=4||f[3].decode_only!=true||f[0].alpha!=std::vector<uint8_t>{4,5,6,7}||f[1].alpha!=std::vector<uint8_t>{11,12,13,14}||f[2].alpha!=std::vector<uint8_t>{21,21,21,21,22,23,24,25})return 2;if(n==3){std::ifstream in(v[1],std::ios::binary|std::ios::ate),expect_in(v[2],std::ios::binary|std::ios::ate);if(!in||!expect_in)return 3;auto size=in.tellg(),expected_size=expect_in.tellg();std::vector<uint8_t> fixture_wire(static_cast<size_t>(size)),expected(static_cast<size_t>(expected_size)),actual;in.seekg(0);expect_in.seekg(0);in.read((char*)fixture_wire.data(),size);expect_in.read((char*)expected.data(),expected_size);Parser fixture(64u*1024u*1024u);std::vector<Frame>frames;for(size_t at=0;at<fixture_wire.size();){auto take=(std::min)(size_t(97),fixture_wire.size()-at);if(!fixture.Push({fixture_wire.data()+at,take},&frames))return 4;at+=take;}for(auto const&x:frames)actual.insert(actual.end(),x.alpha.begin(),x.alpha.end());if(!fixture.Finish()||frames.size()!=3||actual!=expected)return 5;std::cout<<"PASS VFGP fixture alpha bytes="<<actual.size()<<"\n";}std::cout<<"PASS VFGP v1 raw plus v2 raw/RLE and v3 decode-only fragmented records\n";return 0;}
