from pathlib import Path
import subprocess,base64,json,hashlib,tarfile
root=Path('/tmp/viewflow-windows-isolated-root.txt').read_text().strip()
files=['crates/viewflowd/src/'+x for x in ['atlas_peer.rs','atlas_presenter_child.rs','atlas_receiver_presenter.rs']]
Path('/tmp/viewflow-av1-window-source-sha256.json').write_text(json.dumps({f:hashlib.sha256(Path(f).read_bytes()).hexdigest() for f in files},indent=2)+'\n')
with tarfile.open('/tmp/viewflow-av1-window-source.tar.gz','w:gz') as t:
 for f in files:t.add(f,arcname=f)
subprocess.run(['scp','-q','-o','BatchMode=yes','/tmp/viewflow-av1-window-source.tar.gz','wilf@172.16.105.70:'+root.replace(chr(92),'/')+'/av1-window-source.tar.gz'],check=True)
s=r'''$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';Set-Location '__ROOT__';$r=(Get-Location).Path;if(@(Get-CimInstance Win32_Process | Where-Object {$_.ExecutablePath -and $_.ExecutablePath.StartsWith($r,[StringComparison]::OrdinalIgnoreCase)}).Count){throw 'isolated process running'};foreach($ext in @('exe','pdb')){$src=if($ext -eq 'pdb'){'target\release\vf_media_peer.pdb'}else{'target\release\vf-media-peer.exe'};if(Test-Path ('before-av1-window-peer.'+$ext)){if((Get-FileHash $src).Hash -ne (Get-FileHash ('before-av1-window-peer.'+$ext)).Hash){throw 'backup mismatch'}}else{Copy-Item $src ('before-av1-window-peer.'+$ext)}};$before=(Get-FileHash target\release\vf-media-peer.exe).Hash;try{tar.exe -xf av1-window-source.tar.gz;if($LASTEXITCODE){throw 'extract failed'};$env:CARGO_BUILD_JOBS='2';cmd.exe /d /c 'cargo build --release --offline --locked -p viewflowd --bin vf-media-peer > av1-window-build.log 2>&1';if($LASTEXITCODE){Get-Content av1-window-build.log -Tail 30;throw 'build failed'};foreach($ext in @('exe','pdb')){$src=if($ext -eq 'pdb'){'target\release\vf_media_peer.pdb'}else{'target\release\vf-media-peer.exe'};Copy-Item $src ('vf-media-peer-av1.'+$ext)};foreach($filter in @('atlas_presenter_child','atlas_receiver_presenter','atlas_peer')){cmd.exe /d /c ('cargo test --offline --locked -p viewflowd --lib '+$filter+' > av1-window-'+$filter+'-tests.log 2>&1');Get-Content ('av1-window-'+$filter+'-tests.log') -Tail 5;if($LASTEXITCODE){throw ('tests failed '+$filter)}}}finally{foreach($ext in @('exe','pdb')){$dst=if($ext -eq 'pdb'){'target\release\vf_media_peer.pdb'}else{'target\release\vf-media-peer.exe'};Copy-Item ('before-av1-window-peer.'+$ext) $dst}};if((Get-FileHash target\release\vf-media-peer.exe).Hash -ne $before){throw 'restore mismatch'};@{before=$before;restored=(Get-FileHash target\release\vf-media-peer.exe).Hash;candidate=(Get-FileHash vf-media-peer-av1.exe).Hash;native_original=(Get-FileHash native-build\Release\viewflow_windows_composition_preview.exe).Hash;native_av1=(Get-FileHash native-av1-build\Release\viewflow_windows_composition_preview.exe).Hash;time=(Get-Date).ToString('o')}|ConvertTo-Json|Set-Content av1-window-binaries.json;Get-Content av1-window-binaries.json'''.replace('__ROOT__',root)
r=subprocess.run(['ssh','-o','BatchMode=yes','wilf@172.16.105.70','powershell','-NoProfile','-EncodedCommand',base64.b64encode(s.encode('utf-16le')).decode()],capture_output=True,timeout=900)
Path('/tmp/viewflow-av1-window-windows-build.log').write_bytes(r.stdout+r.stderr);print(r.returncode,r.stdout.decode(errors='replace'),r.stderr.decode(errors='replace') if r.returncode else '',flush=True)
for f in ['av1-window-binaries.json','av1-window-build.log','av1-window-atlas_presenter_child-tests.log','av1-window-atlas_receiver_presenter-tests.log','av1-window-atlas_peer-tests.log']:
 subprocess.run(['scp','-q','-o','BatchMode=yes','wilf@172.16.105.70:'+root.replace(chr(92),'/')+'/'+f,'/tmp/viewflow-'+f],check=False)
r.check_returncode()
