from pathlib import Path
import subprocess,base64,json,hashlib
root=Path('/tmp/viewflow-windows-isolated-root.txt').read_text().strip()
s=r'''$ErrorActionPreference='Stop';$r='__ROOT__';$s=Get-CimInstance Win32_Service -Filter "Name='ESRV_SVC_QUEENCREEK'";$p=Get-Process -Id $s.ProcessId;$owned=@(Get-CimInstance Win32_Process|Where-Object {$_.ExecutablePath -and $_.ExecutablePath.StartsWith($r,[StringComparison]::OrdinalIgnoreCase)});$tasks=@(Get-ScheduledTask -TaskName 'ViewflowPerf-IntegratedReceiver','ViewflowPerf-RestoreNowaitSwap','ViewflowPerf-FrameObserver','ViewflowPerf-CoalescePixels','ViewflowPerf-HostBackdrop' -ErrorAction SilentlyContinue);$paths=@('native-nowait-build\Release\viewflow_windows_composition_preview.exe','native-build\Release\viewflow_windows_composition_preview.exe','target\release\vf-media-peer.exe','target\release\vf_media_peer.pdb','native-build\Release\viewflow_windows_composition_preview.pdb','native-build\Release\viewflow_windows_frame_observer.exe','isolated-receiver-runner-nowait-0.exe','isolated-receiver-runner-nowait-1.exe','isolated-receive.json','platform\windows-composition-preview\main.cpp','platform\windows-composition-preview\sparse_shared_visuals.h','platform\windows-composition-preview\sparse_visual_reference.h','platform\windows-composition-preview\sparse_coalesce_capture_test.cpp','platform\windows-composition-preview\sparse_host_backdrop_test.cpp');@{time=(Get-Date).ToString('o');process_id=$p.Id;priority=$p.PriorityClass.ToString();threads=@($p.Threads|Where-Object PriorityLevel -eq 'TimeCritical'|Select-Object Id,PriorityLevel,BasePriority);service_state=$s.State;service_start=$s.StartMode;owned_processes=$owned.Count;owned_tasks=$tasks.Count;experimental_header_exists=(Test-Path ($r+'\platform\windows-composition-preview\stable_surface_layout.h'));hashes=@($paths|ForEach-Object {Get-FileHash ($r+'\'+$_)}|Select-Object Path,Hash)}|ConvertTo-Json -Depth 4'''.replace('__ROOT__',root)
r=subprocess.run(['ssh','-o','BatchMode=yes','wilf@172.16.105.70','powershell','-NoProfile','-EncodedCommand',base64.b64encode(s.encode('utf-16le')).decode()],capture_output=True,timeout=30);r.check_returncode();v=json.loads(r.stdout);h=v['hashes'];b=json.loads(Path('/tmp/viewflow-nowait-binaries.json').read_text());assert h[:8]==b['hashes'];assert not v['experimental_header_exists'] and v['owned_processes']==v['owned_tasks']==0 and v['priority']=='High' and v['service_state']=='Running' and v['service_start']=='Auto'
assert h[8]['Hash'].lower()==hashlib.sha256(Path('/tmp/viewflow-codec-restore-receive-remote.json').read_bytes()).hexdigest()
for i,n in enumerate(['main.cpp','sparse_shared_visuals.h','sparse_visual_reference.h','sparse_coalesce_capture_test.cpp','sparse_host_backdrop_test.cpp']):
 p=Path('platform/windows-composition-preview')/n;assert p.read_bytes()==Path('/tmp/viewflow-before-nowait-'+n).read_bytes();assert h[9+i]['Hash'].lower()==hashlib.sha256(p.read_bytes()).hexdigest()
for n in ['send','receive']:assert Path('/tmp/viewflow-integrated-pair/'+n+'.json').read_bytes()==Path('/tmp/viewflow-codec-restore-'+n+'.json').read_bytes()
Path('/tmp/viewflow-nowait-final-state.json').write_text(json.dumps(v,indent=2)+'\n');print('final baseline sources/binaries/PDB/configs and cleanup verified',v['process_id'],v['priority'],len(v['threads']))
