#include <windows.h>
#include <d3d11.h>
#include <d3d10.h>
#include <mfapi.h>
#include <mferror.h>
#include <mfidl.h>
#include <mftransform.h>
#include <wrl/client.h>
#include <algorithm>
#include <chrono>
#include <cstdio>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>
using Microsoft::WRL::ComPtr;
using Clock=std::chrono::steady_clock;
static void check(HRESULT r,const char*s){if(FAILED(r)){char b[128];sprintf_s(b,"%s: 0x%08lx",s,r);throw std::runtime_error(b);}}
static HRESULT output_type(IMFTransform*d){for(DWORD i=0;;i++){ComPtr<IMFMediaType>t;HRESULT r=d->GetOutputAvailableType(0,i,&t);if(FAILED(r))return r;GUID sub{};t->GetGUID(MF_MT_SUBTYPE,&sub);if(sub==MFVideoFormat_NV12){r=d->SetOutputType(0,t.Get(),0);if(SUCCEEDED(r))return r;}}}
int main(int argc,char**argv){try{if(argc!=3)return 2;check(CoInitializeEx(nullptr,COINIT_MULTITHREADED),"COM");check(MFStartup(MF_VERSION),"MF");GUID subtype=MFVideoFormat_H264;if(std::string(argv[1])=="hevc")subtype=MFVideoFormat_HEVC;if(std::string(argv[1])=="av1")subtype=MFVideoFormat_AV1;
std::ifstream f(argv[2],std::ios::binary);uint32_t magic,w,h;f.read((char*)&magic,4);f.read((char*)&w,4);f.read((char*)&h,4);if(!f||magic!=0x56464342)throw std::runtime_error("fixture header");std::vector<std::vector<BYTE>>packets;std::vector<uint32_t>flags;for(;;){uint32_t n,fl;f.read((char*)&n,4);if(!f)break;f.read((char*)&fl,4);if(n>32*1024*1024)throw std::runtime_error("packet bound");std::vector<BYTE>p(n);f.read((char*)p.data(),n);if(!f)throw std::runtime_error("short packet");packets.push_back(std::move(p));flags.push_back(fl);}
ComPtr<ID3D11Device>device;ComPtr<ID3D11DeviceContext>context;D3D_FEATURE_LEVEL level;check(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,D3D11_CREATE_DEVICE_VIDEO_SUPPORT,nullptr,0,D3D11_SDK_VERSION,&device,&level,&context),"device");ComPtr<ID3D10Multithread>mt;check(device.As(&mt),"multithread");mt->SetMultithreadProtected(TRUE);ComPtr<IMFDXGIDeviceManager>manager;UINT token;check(MFCreateDXGIDeviceManager(&token,&manager),"manager");check(manager->ResetDevice(device.Get(),token),"reset");
MFT_REGISTER_TYPE_INFO info{MFMediaType_Video,subtype};IMFActivate**acts=nullptr;UINT32 count=0;check(MFTEnumEx(MFT_CATEGORY_VIDEO_DECODER,MFT_ENUM_FLAG_ALL|MFT_ENUM_FLAG_SORTANDFILTER,&info,nullptr,&acts,&count),"enum");printf("codec=%s candidates=%u\n",argv[1],count);ComPtr<IMFTransform>d;
for(UINT32 i=0;i<count;i++){ComPtr<IMFTransform>candidate;WCHAR*name=nullptr;UINT32 len;acts[i]->GetAllocatedString(MFT_FRIENDLY_NAME_Attribute,&name,&len);printf("candidate=%ls ",name?name:L"?");CoTaskMemFree(name);HRESULT r=acts[i]->ActivateObject(IID_PPV_ARGS(&candidate));if(SUCCEEDED(r)){ComPtr<IMFAttributes>a;candidate->GetAttributes(&a);UINT32 async=0;if(a){a->GetUINT32(MF_TRANSFORM_ASYNC,&async);a->SetUINT32(MF_LOW_LATENCY,TRUE);}if(async){printf("async=true skipped_by_sync_probe\n");continue;}r=candidate->ProcessMessage(MFT_MESSAGE_SET_D3D_MANAGER,(ULONG_PTR)manager.Get());if(SUCCEEDED(r)){ComPtr<IMFMediaType>in;MFCreateMediaType(&in);in->SetGUID(MF_MT_MAJOR_TYPE,MFMediaType_Video);in->SetGUID(MF_MT_SUBTYPE,subtype);MFSetAttributeSize(in.Get(),MF_MT_FRAME_SIZE,w,h);MFSetAttributeRatio(in.Get(),MF_MT_FRAME_RATE,60,1);r=candidate->SetInputType(0,in.Get(),0);if(SUCCEEDED(r))r=output_type(candidate.Get());}if(SUCCEEDED(r)&&!d)d=candidate;}printf("configure=0x%08lx\n",r);}
for(UINT32 i=0;i<count;i++)acts[i]->Release();CoTaskMemFree(acts);if(!d)throw std::runtime_error("no usable synchronous GPU decoder");check(d->ProcessMessage(MFT_MESSAGE_NOTIFY_BEGIN_STREAMING,0),"begin");check(d->ProcessMessage(MFT_MESSAGE_NOTIFY_START_OF_STREAM,0),"start");D3D11_QUERY_DESC qd{D3D11_QUERY_EVENT,0};ComPtr<ID3D11Query>query;check(device->CreateQuery(&qd,&query),"query");std::vector<Clock::time_point>starts(packets.size());std::vector<double>times;size_t outputs=0;bool allGpu=true;
auto drain=[&](){for(;;){MFT_OUTPUT_DATA_BUFFER out{};DWORD status=0;MFT_OUTPUT_STREAM_INFO si{};check(d->GetOutputStreamInfo(0,&si),"stream info");ComPtr<IMFSample>owned;if(!(si.dwFlags&MFT_OUTPUT_STREAM_PROVIDES_SAMPLES)){MFCreateSample(&owned);ComPtr<IMFMediaBuffer>b;check(MFCreateMemoryBuffer(si.cbSize,&b),"output buffer");owned->AddBuffer(b.Get());out.pSample=owned.Detach();}HRESULT r=d->ProcessOutput(0,1,&out,&status);ComPtr<IMFSample>sample;sample.Attach(out.pSample);if(out.pEvents)out.pEvents->Release();if(r==MF_E_TRANSFORM_NEED_MORE_INPUT)return;if(r==MF_E_TRANSFORM_STREAM_CHANGE){check(output_type(d.Get()),"stream change");continue;}check(r,"output");if(!sample)continue;ComPtr<IMFMediaBuffer>b;check(sample->GetBufferByIndex(0,&b),"buffer");ComPtr<IMFDXGIBuffer>dx;bool gpu=SUCCEEDED(b.As(&dx));allGpu &= gpu;if(!gpu)throw std::runtime_error("non GPU output");ComPtr<ID3D11Texture2D>tex;check(dx->GetResource(IID_PPV_ARGS(&tex)),"texture");LONGLONG pts;check(sample->GetSampleTime(&pts),"pts");context->End(query.Get());context->Flush();auto wait=Clock::now();while(context->GetData(query.Get(),nullptr,0,0)==S_FALSE){if(Clock::now()-wait>std::chrono::seconds(3))throw std::runtime_error("GPU timeout");SwitchToThread();}size_t idx=size_t((pts+83333)/166667);if(idx>=starts.size())throw std::runtime_error("PTS invalid");if(idx>=30)times.push_back(std::chrono::duration<double,std::micro>(Clock::now()-starts[idx]).count());outputs++;}};
for(size_t i=0;i<packets.size();i++){ComPtr<IMFMediaBuffer>b;check(MFCreateMemoryBuffer((DWORD)packets[i].size(),&b),"input buffer");BYTE*p;check(b->Lock(&p,nullptr,nullptr),"lock");memcpy(p,packets[i].data(),packets[i].size());b->Unlock();b->SetCurrentLength((DWORD)packets[i].size());ComPtr<IMFSample>s;MFCreateSample(&s);s->AddBuffer(b.Get());s->SetSampleTime(i*166667);s->SetSampleDuration(166667);s->SetUINT32(MFSampleExtension_CleanPoint,(flags[i]&1)?TRUE:FALSE);starts[i]=Clock::now();check(d->ProcessInput(0,s.Get(),0),"input");drain();}d->ProcessMessage(MFT_MESSAGE_COMMAND_DRAIN,0);drain();if(times.empty())throw std::runtime_error("no output samples");std::sort(times.begin(),times.end());printf("codec=%s outputs=%zu measured=%zu all_gpu=%s host_input_to_output_gpu_fence_us p50=%.1f p95=%.1f p99=%.1f\n",argv[1],outputs,times.size(),allGpu?"true":"false",times[times.size()/2],times[times.size()*95/100],times[times.size()*99/100]);return outputs==packets.size()?0:1;
}catch(const std::exception&e){fprintf(stderr,"ERROR %s\n",e.what());return 1;}}
