#include "gpu_rgba_prepare.cuh"
#include <cuda_runtime_api.h>
#include <algorithm>
#include <cstddef>
#include <cstdio>
#include <cstring>
#include <vector>

namespace {
struct Case { int sw, sh, cx, cy, w, h; bool flip; size_t sp; std::vector<unsigned char> src; };
bool ck(cudaError_t e, const char* s) { if (e == cudaSuccess) return true; std::fprintf(stderr,"FAIL %s: %s\n",s,cudaGetErrorString(e)); return false; }
unsigned char& P(std::vector<unsigned char>& v,size_t p,int x,int y,int c){return v[size_t(y)*p+size_t(x)*4+c];}
const unsigned char& P(const std::vector<unsigned char>& v,size_t p,int x,int y,int c){return v[size_t(y)*p+size_t(x)*4+c];}
void unpremul(std::vector<unsigned char>& v,size_t p,int w,int h){for(int y=0;y<h;y++)for(int x=0;x<w;x++){auto&a=P(v,p,x,y,3);if(!a)P(v,p,x,y,0)=P(v,p,x,y,1)=P(v,p,x,y,2)=0;else if(a!=255)for(int c=0;c<3;c++)P(v,p,x,y,c)=static_cast<unsigned char>(std::min(255,(int(P(v,p,x,y,c))*255+a/2)/a));}}
int seam(const std::vector<unsigned char>&v,size_t p,int w,int h){if(w<=0||h<=2)return-1;int mc=std::max(16,w/3),ms=std::max(16,w/2);for(int y=1;y<std::min(h-1,96);y++){int f=-1,l=-1,n=0;for(int x=0;x<w;x++){auto a=P(v,p,x,y,3),u=P(v,p,x,y-1,3),d=P(v,p,x,y+1,3);if(a<=4&&u>=128&&d>=128){if(f<0)f=x;l=x;n++;}}if(n>=mc&&f>=0&&l-f+1>=ms)return y;}return-1;}
void oracle(const Case&t,std::vector<unsigned char>&o,std::vector<unsigned char>&a,size_t op,size_t ap){std::fill(o.begin(),o.end(),0xcd);std::fill(a.begin(),a.end(),0xcd);for(int y=0;y<t.h;y++){int sy=t.cy+(t.flip?t.h-1-y:y);for(int x=0;x<t.w;x++){for(int c=0;c<4;c++)P(o,op,x,y,c)=P(t.src,t.sp,t.cx+x,sy,c);a[size_t(y)*ap+x]=P(t.src,t.sp,t.cx+x,sy,3);}}unpremul(o,op,t.w,t.h);int s=seam(o,op,t.w,t.h);if(s>=0)for(int x=0;x<t.w;x++){auto aa=P(o,op,x,s,3),u=P(o,op,x,s-1,3),d=P(o,op,x,s+1,3);if(aa<=4&&u>=128&&d>=128){for(int c=0;c<4;c++)P(o,op,x,s,c)=P(o,op,x,s+1,c);a[size_t(s)*ap+x]=P(o,op,x,s,3);}}}
bool run(const Case&t,const char*name){size_t op=size_t(t.w*4+7),ap=size_t(t.w+3);std::vector<unsigned char> want(op*t.h),wa(ap*t.h),got(op*t.h,0xcd),ga(ap*t.h,0xcd),before=t.src,sourceAfter=t.src;oracle(t,want,wa,op,ap);unsigned char *ds=nullptr,*do_=nullptr,*da=nullptr;bool ok=ck(cudaMalloc((void**)&ds,t.src.size()),"malloc source")&&ck(cudaMalloc((void**)&do_,got.size()),"malloc rgba")&&ck(cudaMalloc((void**)&da,ga.size()),"malloc alpha");if(ok)ok=ck(cudaMemcpy(ds,t.src.data(),t.src.size(),cudaMemcpyHostToDevice),"copy source")&&ck(cudaMemcpy(do_,got.data(),got.size(),cudaMemcpyHostToDevice),"init rgba")&&ck(cudaMemcpy(da,ga.data(),ga.size(),cudaMemcpyHostToDevice),"init alpha");viewflow::gpu::RgbaPrepare p{ds,t.sp,t.sw,t.sh,t.cx,t.cy,t.w,t.h,t.flip,do_,op,da,ap};if(ok)ok=ck(viewflow::gpu::prepareRgba(p,0),"prepare")&&ck(cudaDeviceSynchronize(),"sync");if(ok)ok=ck(cudaMemcpy(got.data(),do_,got.size(),cudaMemcpyDeviceToHost),"read rgba")&&ck(cudaMemcpy(ga.data(),da,ga.size(),cudaMemcpyDeviceToHost),"read alpha")&&ck(cudaMemcpy(sourceAfter.data(),ds,t.src.size(),cudaMemcpyDeviceToHost),"read source");if(ds)ok=ck(cudaFree(ds),"free source")&&ok;if(do_)ok=ck(cudaFree(do_),"free rgba")&&ok;if(da)ok=ck(cudaFree(da),"free alpha")&&ok;if(!ok)return false;if(sourceAfter!=before){std::fprintf(stderr,"FAIL %s: source mutated\n",name);return false;}if(got!=want||ga!=wa){for(int y=0;y<t.h;y++)if(std::memcmp(got.data()+size_t(y)*op,want.data()+size_t(y)*op,size_t(t.w)*4)||std::memcmp(ga.data()+size_t(y)*ap,wa.data()+size_t(y)*ap,t.w)){std::fprintf(stderr,"FAIL %s: oracle mismatch row=%d expected_seam=%d\n",name,y,seam(want,op,t.w,t.h));break;}return false;}std::printf("PASS %s\n",name);return true;}
Case make(int sw,int sh,int cx,int cy,int w,int h,bool flip){Case t{sw,sh,cx,cy,w,h,flip,size_t(sw*4+11),std::vector<unsigned char>(size_t(sh)*(sw*4+11))};for(int y=0;y<sh;y++)for(int x=0;x<sw;x++){P(t.src,t.sp,x,y,0)=static_cast<unsigned char>(x*7+y*3);P(t.src,t.sp,x,y,1)=static_cast<unsigned char>(x*5+y*11);P(t.src,t.sp,x,y,2)=static_cast<unsigned char>(x*13+y*2);P(t.src,t.sp,x,y,3)=200;}return t;}
void alpha(Case&t,int y,unsigned char v,int l=0,int r=-1){if(r<0)r=t.w;int sy=t.cy+(t.flip?t.h-1-y:y);for(int x=l;x<r;x++)P(t.src,t.sp,t.cx+x,sy,3)=v;}
}
int main(){bool ok=true;auto exhaustive=make(65536,1,0,0,65536,1,false);for(int i=0;i<65536;i++){int x=i&255,a=i>>8;P(exhaustive.src,exhaustive.sp,i,0,0)=static_cast<unsigned char>(x);P(exhaustive.src,exhaustive.sp,i,0,1)=static_cast<unsigned char>(x);P(exhaustive.src,exhaustive.sp,i,0,2)=static_cast<unsigned char>(x);P(exhaustive.src,exhaustive.sp,i,0,3)=static_cast<unsigned char>(a);}ok=run(exhaustive,"exhaustive_alpha_channel_lut")&&ok;auto t=make(37,9,5,2,23,5,true);ok=run(t,"crop_flip_padded_pitch")&&ok;auto s=make(64,8,0,0,64,8,false);alpha(s,1,2);alpha(s,2,200);alpha(s,3,200);alpha(s,4,2);alpha(s,5,200);ok=run(s,"two_qualified_seams_only_first")&&ok;auto l=make(32,6,0,0,32,6,false);alpha(l,1,2,0,8);alpha(l,2,200,0,8);ok=run(l,"local_seam_below_column_threshold")&&ok;auto n=make(15,5,0,0,15,5,false);alpha(n,1,2);alpha(n,2,200);ok=run(n,"width_below_sixteen_no_seam")&&ok;if(!ok)return 1;std::puts("PASS gpu RGBA prepare crop/flip/seam/unpremultiply oracle suite");}
